version: '3.1'
services:
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - "80:80"
    networks:
      - frontend
    deploy:
      replicas: 2

  redis:
    image: redis:3.2
    networks:
      - frontend

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
  db:
    image: postgres:9.4
    networks:
      - backend

  result: 
    image: dockersamples/examplevotingapp_result:before
    ports:
      - "5000:80"
    networks:
      - backend

networks:
  frontend: 
  backend: